discord:
  bot:
    activity: dev-environment...

api:
  stonehaven:
    farmrun-item-service:
      base-url: https://api-staging.stonehaven.fr/farmrun/item
    farmrun-player-service:
      base-url: https://api-staging.stonehaven.fr/farmrun/player