name: DiscordCommitMessage

on:
  push:
    branches: [ "dev", "master" ]
  pull_request:
    branches: [ "dev", "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_COMMIT_WEBHOOK_URL }}
          embed-title: "New commit on discord-bot"
          embed-description: "${{ github.event.head_commit.message }}"
          username: "${{ github.event.pusher.name }}"
          embed-footer-text: "${{github.ref}}"